### ISSUE TITLE
Reasoning behind secret length

### ISSUE THREAD

**Issue by sourabhmarathe** [rhyzomatic/OT.py#2]
Hey, I am just wondering if there is a reason for secret length being 44. (I'm trying to use this to implement a further primitive on top of OT).

**Comment by wbernoudy** [comment]
Hey! I don't think there was any particular reasoning behind it. Basically, the secret length just needs to be less than Alice's public key (N). So if N has 512 bits, secrets should be <= 511 bits to be safe.

Also I found a major bug thanks to having to look at my code and the paper again, thanks :)

If you don't mind me asking, what are you thinking of building? I just got this script working to the point of the example, but I would be interested in making it more usable as an import if it would help.

**Comment by sourabhmarathe** [comment]
Hi William,
Originally I was trying to build a new primitive called Oblivious Pseudo Random Function (OPRF) that makes use of OT. I have been implementing my own OT in C++ but I may reconsider this implementation in Python if I can get it to work. It would save me a lot of time. Thanks for responding. I'll try to get this to work one more time later today.

**Comment by wbernoudy** [comment]
I made `secret_length` a proper parameter instead of a global variable in f7a484b868b997259d263068bb37f06cc7ce5ac9. Hopefully that also helps clear it up.
